; Listing generated by Microsoft (R) Optimizing Compiler Version 19.42.34433.0 

	TITLE	C:\Users\Achmed\Git_Repos_AH1\My_First_C_Program\words.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_words
_DATA	SEGMENT
_words	DD	FLAT:$SG7537
	DD	FLAT:$SG7538
	DD	FLAT:$SG7539
	DD	FLAT:$SG7540
	DD	FLAT:$SG7541
	DD	FLAT:$SG7542
	DD	FLAT:$SG7543
	DD	FLAT:$SG7544
	DD	FLAT:$SG7545
	DD	FLAT:$SG7546
	DD	FLAT:$SG7547
	DD	FLAT:$SG7548
	DD	FLAT:$SG7549
	DD	FLAT:$SG7550
	DD	FLAT:$SG7551
	DD	FLAT:$SG7552
	DD	FLAT:$SG7553
	DD	00H
$SG7537	DB	'abort', 00H
	ORG $+2
$SG7538	DB	'acorn', 00H
	ORG $+2
$SG7539	DB	'acryl', 00H
	ORG $+2
$SG7540	DB	'hanns', 00H
	ORG $+2
$SG7541	DB	'heinz', 00H
	ORG $+2
$SG7542	DB	'herby', 00H
	ORG $+2
$SG7543	DB	'erwin', 00H
	ORG $+2
$SG7544	DB	'erich', 00H
	ORG $+2
$SG7545	DB	'emile', 00H
	ORG $+2
$SG7546	DB	'erpel', 00H
	ORG $+2
$SG7547	DB	'eumel', 00H
	ORG $+2
$SG7548	DB	'sandy', 00H
	ORG $+2
$SG7549	DB	'sammy', 00H
	ORG $+2
$SG7550	DB	'sadie', 00H
	ORG $+2
$SG7551	DB	'sofie', 00H
	ORG $+2
$SG7552	DB	'susie', 00H
	ORG $+2
$SG7553	DB	'suzie', 00H
_DATA	ENDS
END
